# Generated by Django 4.2.2 on 2026-08-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_product_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': 'Cart Orders'},
        ),
        migrations.AlterModelOptions(
            name='wishlist_model',
            options={'verbose_name_plural': 'Wishlists'},
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartorderproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartorderproducts',
            name='total',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='2.99', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
