# Generated by Django 4.2.2 on 2026-08-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_category_cid_alter_product_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deal_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
