# Generated by Django 4.2.2 on 2026-08-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_product_deal_end_date_product_deal_of_the_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_top_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_top_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
