# Generated by Django 4.2.2 on 2026-09-19 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_product_is_top_rated_product_is_top_selling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.product'),
        ),
        migrations.AddField(
            model_name='cartorderproducts',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.vendor'),
        ),
    ]
