# Generated by Django 4.2.2 on 2026-08-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='HomePageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Theme', max_length=100)),
                ('primary_color', models.CharField(blank=True, help_text='e.g. #ff0000', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Home Pages Theme',
                'verbose_name_plural': 'Home Pages Theme',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Site', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Facebook', max_length=100)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, help_text='e.g. fab fa-facebook-f', max_length=50, null=True)),
                ('image_icon', models.ImageField(blank=True, null=True, upload_to='settings/social/')),
            ],
            options={
                'verbose_name': 'Socail links',
                'verbose_name_plural': 'Socail links',
            },
        ),
        migrations.CreateModel(
            name='SupportNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='e.g. Sales, Support', max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Support Numbers',
                'verbose_name_plural': 'Support Numbers',
            },
        ),
    ]
