# Generated by Django 4.2.2 on 2026-08-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
