# Generated by Django 4.2.2 on 2026-08-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_footerlinkcolumn_sitesettings_footer_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='image_icon',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='url',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Leave blank to hide Facebook icon', null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Leave blank to hide Instagram icon', null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='pinterest_url',
            field=models.URLField(blank=True, help_text='Leave blank to hide Pinterest icon', null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Leave blank to hide Twitter icon', null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Leave blank to hide YouTube icon', null=True),
        ),
    ]
