# Generated by Django 4.2.2 on 2026-08-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_remove_sociallink_icon_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='developer_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='developer_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
