# Generated by Django 4.2.2 on 2026-08-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_sitesettings_developer_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cta/')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_heading', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Call To Action',
                'verbose_name_plural': 'Call To Action',
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('link_text', models.CharField(blank=True, default='Shop Now', max_length=50, null=True)),
                ('link_url', models.CharField(blank=True, default='#', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Home Banner',
                'verbose_name_plural': 'Home Banners',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('link_text', models.CharField(blank=True, default='Shop Now', max_length=50, null=True)),
                ('link_url', models.CharField(blank=True, default='#', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
